# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='User Token')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=200, verbose_name='User Password')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='Register Time')),
                ('friends', models.ManyToManyField(to='account.User')),
            ],
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
