# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message Content')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='Send Time')),
                ('receive_flag', models.BooleanField(verbose_name='Received')),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to='account.User')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='account.User')),
            ],
        ),
    ]
